[server]
port = 8501
address = "0.0.0.0"
baseUrlPath = ""
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200

[browser]
serverAddress = "localhost"
gatherUsageStats = false
serverPort = 8501

[theme]
primaryColor = "#007bff"
backgroundColor = "#f5f7fa"
secondaryBackgroundColor = "#e9ecef"
textColor = "#212529"
font = "sans serif"